# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.cache/wt [current_project]
set_property parent.project_path C:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/ip/cpuToCtrl_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/modules/adv7511/adv7511InitFile.mif
  C:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/modules/ov7670/ov7670InitFile.mif
  C:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/modules/oled/oledCharFile.mif
}
read_vhdl -library xil_defaultlib C:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/hdl/cam2hdmi_bd_wrapper.vhd
add_files C:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/cam2hdmi_bd.bd
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_clk_wiz_0/cam2hdmi_bd_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_clk_wiz_0/cam2hdmi_bd_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_clk_wiz_0/cam2hdmi_bd_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_rst_clk_wiz_100M_0/cam2hdmi_bd_rst_clk_wiz_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_rst_clk_wiz_100M_0/cam2hdmi_bd_rst_clk_wiz_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_rst_clk_wiz_100M_0/cam2hdmi_bd_rst_clk_wiz_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_processing_system7_0_0/cam2hdmi_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_axi_gpio_0_1/cam2hdmi_bd_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_axi_gpio_0_1/cam2hdmi_bd_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_axi_gpio_0_1/cam2hdmi_bd_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_xbar_0/cam2hdmi_bd_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/ip/cam2hdmi_bd_auto_pc_0/cam2hdmi_bd_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/nsheu/OneDrive/Desktop/miniprojekt/memory/memory.srcs/sources_1/bd/cam2hdmi_bd/cam2hdmi_bd_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/constraints/cam2hdmi_pins.xdc
set_property used_in_implementation false [get_files C:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/constraints/cam2hdmi_pins.xdc]

read_xdc C:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/constraints/cam2hdmi_timing.xdc
set_property used_in_implementation false [get_files C:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/constraints/cam2hdmi_timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cam2hdmi_bd_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef -incremental_synth cam2hdmi_bd_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cam2hdmi_bd_wrapper_utilization_synth.rpt -pb cam2hdmi_bd_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
