# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/constraints/cam2hdmi_pins.xdc

# XDC: C:/Users/nsheu/OneDrive/Desktop/DIGME/miniprojekt/mulo/project/constraints/cam2hdmi_timing.xdc

# Block Designs: bd/cam2hdmi_bd/cam2hdmi_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd || ORIG_REF_NAME==cam2hdmi_bd} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_adv7511_0_0/cam2hdmi_bd_adv7511_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_adv7511_0_0 || ORIG_REF_NAME==cam2hdmi_bd_adv7511_0_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_clk_wiz_0/cam2hdmi_bd_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_clk_wiz_0 || ORIG_REF_NAME==cam2hdmi_bd_clk_wiz_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_rst_clk_wiz_100M_0/cam2hdmi_bd_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_rst_clk_wiz_100M_0 || ORIG_REF_NAME==cam2hdmi_bd_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_util_vector_logic_0_0/cam2hdmi_bd_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_util_vector_logic_0_0 || ORIG_REF_NAME==cam2hdmi_bd_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_processing_system7_0_0/cam2hdmi_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_processing_system7_0_0 || ORIG_REF_NAME==cam2hdmi_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_ps7_0_axi_periph_0/cam2hdmi_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==cam2hdmi_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_axi_gpio_0_1/cam2hdmi_bd_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_axi_gpio_0_1 || ORIG_REF_NAME==cam2hdmi_bd_axi_gpio_0_1} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_xbar_0/cam2hdmi_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_xbar_0 || ORIG_REF_NAME==cam2hdmi_bd_xbar_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_sdpRAM_0_0/cam2hdmi_bd_sdpRAM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_sdpRAM_0_0 || ORIG_REF_NAME==cam2hdmi_bd_sdpRAM_0_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_roi_0_0/cam2hdmi_bd_roi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_roi_0_0 || ORIG_REF_NAME==cam2hdmi_bd_roi_0_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_axiImage_0_0/cam2hdmi_bd_axiImage_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_axiImage_0_0 || ORIG_REF_NAME==cam2hdmi_bd_axiImage_0_0} -quiet] -quiet

# IP: bd/cam2hdmi_bd/ip/cam2hdmi_bd_auto_pc_0/cam2hdmi_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cam2hdmi_bd_auto_pc_0 || ORIG_REF_NAME==cam2hdmi_bd_auto_pc_0} -quiet] -quiet

# XDC: bd/cam2hdmi_bd/cam2hdmi_bd_ooc.xdc
